### ISSUE TITLE
Does this work against Polygon?

### ISSUE THREAD

**Issue by diwu1989** [unstoppabledomains/resolution-go#19]
In the read me it says `Library supports Ethereum mainnet and Zilliqa mainnet only.`

Does this not work against Polygon?
What RPC endpoint should I use for Polygon resolutions?

**Comment by DancingAxolotl** [comment]
Hey @diwu1989!
Yes, the library supports Polygon domains. The readme should be updated. 
By default the `UnsBuilder` should configure resolution for both L1 and L2. So the examples in the readme should work for L2 domains. Let me know if you have any issues.

If you want a custom RPC provider, you can use alchemy
https://www.alchemy.com/layer2/polygon

**Comment by mikeymop** [comment]
Hello,

I just tried to resolve an L2 domain and have issues.
When using 

`"github.com/unstoppabledomains/resolution-go"`

```go
func ResolveAddress(domainName string, token string) string {
	uns, _ := resolution.NewUnsBuilder().Build()
	address, _ := uns.Addr(domainName, token)

	return address
}
```

```
 Error getting records for mikeymop.x Domain is not registered. Domain name: mikeymop.x. Namehash: 
exit status 1
```

If I try with `"github.com/unstoppabledomains/resolution-go/v2"`
I get the following error:

```
 Error connecting to ethereum Invalid UNS configuration value of network for Layer 1
```

This is with v1.1.2.

**Comment by sammyluo** [comment]
@mikeymop Sorry for the late reply. This issue should be fixed by our latest release. Can you give a try again, please? Thanks!
