### ISSUE TITLE
Is there plan for coredns plugin for resolution on enterprise network?

### ISSUE THREAD

**Issue by soumyajitsamanta** [unstoppabledomains/resolution-go#21]
Hi Team,
CoreDNS product has plugin for resolving .eth domains using https://coredns.io/explugins/ens/ , is similar plugin going to be made for unstoppable domains resolution as well.

**Comment by DancingAxolotl** [comment]
Hey @soumyajitsamanta! Thanks for reaching out!
We currently don't have plans to make a similar plugin.
